# What standard to use. This is optional and defaults to VHDL2008.
standard = "2008"

[lint]
unused = 'error' # Upgrade the 'unused' diagnostic to the 'error' severity
unnecessary_work_library = true

# The initial version of this file was copied verbatim from the `vhdl_ls`
# README.md.
# File names are either absolute or relative to the parent folder of the vhdl_ls.toml file


[libraries]
ex3.files = [
  "src/ex3/ex3.vhdl"
]
ex4_lib1.files = [
  "src/ex4/lib1/lib1.vhdl"
]
ex4.files = [
  "src/ex4/ex4.vhdl"
]

# Libraries can be marked as third-party to disable some analysis warnings, such as unused declarations
#UNISIM.files = [
    #'C:\Xilinx\Vivado\2023.1\data\vhdl\src\unisims\unisim_VCOMP.vhd',
#]
#UNISIM.is_third_party = true
